### ISSUE TITLE
大神，请问下我解析失败

### ISSUE THREAD

**Issue by zmm135544** [ithere/douyindownload-miniapp#1]
我用开发者工具，预览，然后提示解析失败，这是哪里问题

**Comment by ithere** [comment]
> 我用开发者工具，预览，然后提示解析失败，这是哪里问题

你看下接口返回值和提交的分享链接是否正确。

**Comment by zmm135544** [comment]
不知道怎么看，我是复制你的文件去项目里面，不复制app.js这个JS ，就提示解析失败，复制这个JS就提示错误 ，有联系方式么，或者更新一下代码

**Comment by zx870283980** [comment]
解析失败，报错

**Comment by ithere** [comment]
> 不知道怎么看，我是复制你的文件去项目里面，不复制app.js这个JS ，就提示解析失败，复制这个JS就提示错误 ，有联系方式么，或者更新一下代码

服务器被我升级内核搞宕机了  你在看下 是否有问题

**Comment by ithere** [comment]
> 解析失败，报错

服务器被我升级内核搞宕机了  你在看下 是否有问题

**Comment by zmm135544** [comment]
> 服务器被我升级内核搞停机机了你在看下是否有问题
我找到了解析API，我要怎么加进去才可以解析成功，可不可以修改下代码重新上传替换API就可以解析
