### ISSUE TITLE
微信公众号平台服务器域名需要添加哪些合法域名

### ISSUE THREAD

**Issue by AckyLin** [ithere/douyindownload-miniapp#4]
request合法域名
downloadFile合法域名

**Comment by ithere** [comment]
> request合法域名
> downloadFile合法域名

使用微信开发者工具，不要勾选调试模式 然后运行 在调试控制台里会与报错信息，看哪个域名爆红的 就都加到你的微信后台里

**Comment by AckyLin** [comment]
谢谢
需要添加以下
https://v1-dy.ixigua.com
https://v2-dy.ixigua.com
https://v3-dy.ixigua.com
https://v4-dy.ixigua.com
https://v5-dy.ixigua.com
https://v6-dy.ixigua.com
https://v7-dy.ixigua.com
https://v8-dy.ixigua.com
https://v9-dy.ixigua.com
https://aweme.snssdk.com

**Comment by laxin** [comment]
解析出来的域名地址非常多，看似是动态的，要怎么绕过downloadFile合法域名

**Comment by IndigoMagic** [comment]
需要加到downloadFile的合法域名非常多， v27-dy.ixigua.com ，v6-dy-y.ixigua.com 等等，虽然有规律但是数量超过小程序允许添加的20个，这个要怎么处理呢
