### ISSUE TITLE
解析出来的域名地址非常多，看似是动态的，要怎么绕过downloadFile合法域名

### ISSUE THREAD

**Issue by laxin** [ithere/douyindownload-miniapp#7]

**Comment by ithere** [comment]
一种方法 加几个常用地址到微信后台，轮询匹配到后再下载，另外一种 自己写后台中转 先下到服务器在用小程序从服务器下载，最后一种使用中间件 把视频数据获取到直接返回给小程序 由小程序进行下载。后面两种对服务器的带宽有要求 1m的话就会非常慢

**Comment by axinjs** [comment]
怎么使用中间件啊 求解
